export const modules = [
  {
    id: 1,
    slug: "skenario-spesifikasi",
    title: "Skenario & spesifikasi",
    category: "Fondasi",
    minutes: 20,
    unit: "J.620100.009.01",
    summary:
      "Pahami kebutuhan Kopi Ulee Kareng sebelum menulis baris kode pertama.",
    goals: [
      "Jelaskan tujuan, pengguna, input, proses, dan output.",
      "Bedakan portal belajar Next.js ini dengan proyek latihan Laravel.",
      "Kenali satu entitas inti: products.",
    ],
    body: "Anda berperan sebagai Pemrogram Junior. Kopi Ulee Kareng membutuhkan landing page yang membaca produk dari database serta halaman pengelolaan CRUD. Hasil minimum: navbar, hero, tentang, keunggulan, produk, kontak, footer; daftar, tambah, edit, dan hapus produk; validasi dan pesan umpan balik. Latihan Laravel dibatasi satu tabel, tanpa autentikasi, pembayaran, keranjang, API, dan deployment. Batasan ini tidak membatasi teknologi portal belajar.",
    code: "Input   → nama_produk, deskripsi, harga, gambar\nProses  → validasi → simpan / baca / ubah / hapus\nOutput  → landing page, tabel, form, pesan validasi",
    checkpoint: "Tuliskan alur tambah produk dengan kalimat sendiri.",
    reference: 2,
  },
  {
    id: 2,
    slug: "database-mvc",
    title: "Database & arsitektur MVC",
    category: "Fondasi",
    minutes: 35,
    unit: "J.620100.004.02",
    summary:
      "Rancang tabel products dan ikuti perjalanan request sampai ke database.",
    goals: [
      "Gunakan nama_produk maksimal 100 karakter.",
      "Jelaskan unsignedInteger dan nullable.",
      "Bedakan peran route, controller, model, dan view.",
    ],
    body: "Tabel products memiliki id, nama_produk, deskripsi, harga, gambar, created_at, dan updated_at. Harga berupa integer nonnegatif dalam rupiah. Gambar menyimpan nama file yang telah tersedia di public/images, bukan upload. Route menerima request, controller mengatur proses, model mengakses MySQL, dan Blade merender respons.",
    code: "Schema::create('products', function (Blueprint $table) {\n    $table->id();\n    $table->string('nama_produk', 100);\n    $table->text('deskripsi');\n    $table->unsignedInteger('harga');\n    $table->string('gambar')->nullable();\n    $table->timestamps();\n});",
    checkpoint:
      "Tunjukkan setiap field pada database dan jelaskan tipe datanya.",
    reference: 5,
  },
  {
    id: 3,
    slug: "landing-crud",
    title: "Landing page & CRUD",
    category: "Implementasi",
    minutes: 60,
    unit: "J.620100.017.02",
    summary:
      "Hubungkan halaman publik dan pengelolaan produk melalui resource route.",
    goals: [
      "Buat halaman daftar, tambah, edit, dan hapus.",
      "Tampilkan produk dinamis pada landing page.",
      "Sediakan empty state dan konfirmasi hapus.",
    ],
    body: "Halaman / menampilkan landing page. /produk menampilkan daftar, /produk/create menampilkan form tambah, dan /produk/{produk}/edit menampilkan form edit. Method store dan update memvalidasi input sebelum menyimpan. destroy menghapus produk setelah konfirmasi. Resource route tidak memerlukan show pada studi kasus ini.",
    code: "Route::get('/', [ProductController::class, 'landing'])\n    ->name('landing');\nRoute::resource('produk', ProductController::class)\n    ->except(['show']);\n\n// Controller\npublic function index() {\n    $products = Product::query()->latest()->get();\n    return view('produk.index', compact('products'));\n}",
    checkpoint:
      "Uji satu siklus create → read → update → delete pada Laravel lokal.",
    reference: 8,
  },
  {
    id: 4,
    slug: "validasi-standar",
    title: "Validasi & standar kode",
    category: "Implementasi",
    minutes: 30,
    unit: "J.620100.016.01",
    summary:
      "Tolak input tidak valid dan berikan pesan yang membantu pengguna.",
    goals: [
      "Nama dan deskripsi wajib.",
      "Harga wajib integer dengan minimal 0.",
      "Simpan hanya data hasil validasi.",
    ],
    body: "Validasi bukan $fillable. Validasi memeriksa input, sedangkan $fillable membatasi atribut mass assignment. Gunakan nama_produk secara konsisten pada migration, model, controller, form, dan Blade. Tampilkan pesan @error serta old() untuk mempertahankan input ketika validasi gagal.",
    code: "$validated = $request->validate([\n    'nama_produk' => 'required|string|max:100',\n    'deskripsi' => 'required|string',\n    'harga' => 'required|integer|min:0',\n    'gambar' => 'nullable|string|max:255',\n]);\nProduct::query()->create($validated);\nreturn redirect()->route('produk.index')\n    ->with('success', 'Produk berhasil ditambahkan.');",
    checkpoint: "Coba nama kosong, harga huruf, harga negatif, dan harga 0.",
    reference: 8,
  },
  {
    id: 5,
    slug: "debugging-pengujian",
    title: "Debugging & pengujian",
    category: "Verifikasi",
    minutes: 40,
    unit: "J.620100.033.02",
    summary: "Buktikan fungsi dengan TC-01 sampai TC-10 dan feature test.",
    goals: [
      "Reproduksi minimal satu bug.",
      "Catat expected dan actual result secara terpisah.",
      "Jalankan minimal satu feature test Laravel.",
    ],
    body: "Debugging: reproduksi, baca pesan error, catat file dan baris, buat dugaan penyebab, perbaiki bagian terkecil, lalu uji ulang. Lembar uji di portal menyediakan sepuluh skenario dari dokumen. Hasilnya harus diisi berdasarkan aplikasi Laravel yang benar-benar dijalankan; menyelesaikan modul tidak membuktikan aplikasi lulus.",
    code: "php artisan route:list\nphp artisan test\n\n// tests/Feature/ProductFlowTest.php\nuse Illuminate\\Foundation\\Testing\\RefreshDatabase;\n\n// Di dalam class TestCase gunakan trait RefreshDatabase.\npublic function test_landing_page_can_be_opened(): void\n{\n    $this->get('/')->assertStatus(200);\n}",
    checkpoint: "Dokumentasikan satu bug dan hasil pengujian ulangnya.",
    reference: 15,
  },
  {
    id: 6,
    slug: "persiapan-lingkungan",
    title: "Persiapan lingkungan Laravel",
    category: "Fondasi",
    minutes: 30,
    unit: "J.620100.010.01",
    summary: "Siapkan PHP 8.2, Composer, Laravel 12, dan MySQL.",
    goals: [
      "Periksa versi sebelum instalasi.",
      "Atur .env tanpa menimpa konfigurasi yang sudah ada.",
      "Pastikan hanya satu layanan MySQL memakai port 3306.",
    ],
    body: "Gunakan Laragon atau XAMPP. Jalankan MySQL, buka terminal proyek, dan pastikan PHP serta Composer dikenali. Buat database kopi_ulee_kareng. Gunakan APP_DEBUG=true hanya untuk latihan lokal. Jangan menyerahkan .env yang berisi kredensial.",
    code: 'php -v\ncomposer --version\ncomposer create-project laravel/laravel kopi-ulee-kareng "^12.0"\ncd kopi-ulee-kareng\nphp artisan --version\nphp artisan key:generate\nphp artisan config:clear\nphp artisan serve',
    checkpoint:
      "Catat versi PHP, Composer, Laravel, serta hasil koneksi database.",
    reference: 4,
  },
  {
    id: 7,
    slug: "model-seeder",
    title: "Model Eloquent & seeder",
    category: "Implementasi",
    minutes: 35,
    unit: "J.620100.017.02",
    summary: "Pahami mass assignment, casting, collection, dan data awal.",
    goals: [
      "Isi $fillable sesuai data dictionary.",
      "Bedakan casts() dan tipe kolom migration.",
      "Seed tiga produk contoh.",
    ],
    body: "Model Product merepresentasikan products. casts() mengubah representasi atribut saat dibaca, bukan struktur database. Seeder menjalankan foreach pada array produk dan membuat record. Hindari menjalankan seeder berulang tanpa memahami potensi duplikasi.",
    code: "protected $fillable = [\n    'nama_produk', 'deskripsi', 'harga', 'gambar',\n];\nprotected function casts(): array {\n    return ['harga' => 'integer'];\n}\n\n// Di dalam ProductSeeder::run()\nProduct::query()->create([\n    'nama_produk' => 'Kopi Sanger',\n    'deskripsi' => 'Perpaduan kopi dan susu yang lembut.',\n    'harga' => 18000,\n    'gambar' => 'kopi-sanger.jpg',\n]);",
    checkpoint: "Tunjukkan tiga record hasil seeder dan jelaskan prosesnya.",
    reference: 7,
  },
  {
    id: 8,
    slug: "blade-form",
    title: "Blade, form & keamanan",
    category: "Implementasi",
    minutes: 45,
    unit: "J.620100.016.01",
    summary: "Bangun layout, form partial, error field, dan method spoofing.",
    goals: [
      "Gunakan @csrf pada form mutasi.",
      "Pahami @method untuk PUT dan DELETE.",
      "Tampilkan data dengan escaping Blade.",
    ],
    body: "Gunakan {{ }} untuk output yang di-escape. @csrf menyertakan token CSRF; @method mengirim method selain GET/POST melalui form. Form partial dipakai bersama pada create dan edit. Gunakan @forelse untuk daftar yang mungkin kosong.",
    code: '<form method="POST" action="{{ route(\'produk.update\', $produk) }}">\n    @csrf\n    @method(\'PUT\')\n    <label for="nama_produk">Nama produk</label>\n    <input id="nama_produk" name="nama_produk"\n        value="{{ old(\'nama_produk\', $produk->nama_produk) }}">\n    @error(\'nama_produk\') <p>{{ $message }}</p> @enderror\n    <button type="submit">Simpan perubahan</button>\n</form>',
    checkpoint: "Pastikan input tetap tampil setelah validasi gagal.",
    reference: 11,
  },
  {
    id: 9,
    slug: "css-responsif",
    title: "CSS & tampilan responsif",
    category: "Implementasi",
    minutes: 30,
    unit: "J.620100.016.01",
    summary: "Buat tampilan yang terbaca dan nyaman pada perangkat kecil.",
    goals: [
      "Gunakan CSS lokal untuk proyek latihan.",
      "Uji navigasi keyboard dan ukuran layar kecil.",
      "Sediakan fallback gambar.",
    ],
    body: "Latihan tidak membutuhkan Vite/NPM untuk CSS. Simpan stylesheet di public/css/style.css. Berikan label pada input, pesan empty state, kontras memadai, dan tabel yang dapat digulir di layar kecil. Gunakan nama file gambar yang tersedia atau kopi-default.jpg.",
    code: ".products {\n  display: grid;\n  grid-template-columns: repeat(auto-fit, minmax(min(100%, 250px), 1fr));\n  gap: 1.5rem;\n}\n.table-wrapper { overflow-x: auto; }\nimg { max-width: 100%; height: auto; }\n:focus-visible { outline: 3px solid #c85628; }",
    checkpoint: "Uji pada lebar 375px, desktop, dan pembesaran teks 200%.",
    reference: 12,
  },
  {
    id: 10,
    slug: "dokumentasi-portofolio",
    title: "Dokumentasi & portofolio",
    category: "Verifikasi",
    minutes: 30,
    unit: "J.620100.023.02",
    summary: "Siapkan README, bukti kerja, log debugging, dan laporan uji.",
    goals: [
      "Tuliskan cara menjalankan proyek.",
      "Lampirkan bukti asli hasil pekerjaan.",
      "Siapkan presentasi lima menit.",
    ],
    body: "Portofolio berisi source code, README, screenshot landing/CRUD, hasil pengujian, log debugging, dan refleksi. Jangan menyertakan .env atau data rahasia. Presentasi menjelaskan kebutuhan, alur MVC, demo CRUD, validasi, dan hasil uji. Ekspor catatan dari portal membantu menyusun laporan; hasil pengujian tidak diisi otomatis.",
    code: "# Kopi Ulee Kareng\n## Tujuan dan fitur\n## Kebutuhan perangkat\n## Instalasi dan konfigurasi database\n## Cara menjalankan\n## Struktur proyek\n## Pengujian dan hasil aktual\n## Debugging dan perbaikan\n## Bukti screenshot dan refleksi",
    checkpoint: "Gunakan halaman Portofolio untuk memeriksa kelengkapan bukti.",
    reference: 16,
  },
  {
    id: 11,
    slug: "pmo-asesor",
    title: "Latihan lisan & PMO",
    category: "Verifikasi",
    minutes: 20,
    unit: "J.620100.033.02",
    summary: "Latih penjelasan konsep tanpa sekadar menghafal sintaks.",
    goals: [
      "Jelaskan create vs store dan edit vs update.",
      "Tunjukkan Route Model Binding.",
      "Jelaskan bukti hasil uji.",
    ],
    body: "Pertanyaan lisan membantu memeriksa pemahaman. Jelaskan jawaban dengan menunjuk file pada proyek sendiri. Penanda selesai dan skor portal adalah hasil latihan pribadi, bukan keputusan kompetensi resmi. Keputusan kompeten atau belum kompeten tetap pada asesor dan LSP.",
    code: "Browser → Route → Controller → Model → MySQL\n                           ↓\n                     View / Redirect\n\ncreate(): form baru      store(): simpan baru\nedit(): form perubahan  update(): simpan perubahan",
    checkpoint:
      "Jawab lima flashcard tanpa melihat jawaban, lalu cek penjelasannya.",
    reference: 17,
  },
  {
    id: 12,
    slug: "simulasi-akhir",
    title: "Simulasi & refleksi akhir",
    category: "Verifikasi",
    minutes: 25,
    unit: "J.620100.033.02",
    summary: "Satukan implementasi, debugging, pengujian, dan bukti kerja.",
    goals: [
      "Jalankan seluruh TC dengan data normal dan invalid.",
      "Catat bagian yang belum dikuasai.",
      "Periksa kembali skema dan MUK resmi.",
    ],
    body: "Kerjakan simulasi dari analisis kebutuhan sampai penyerahan. Dokumen memuat durasi yang tidak konsisten: identitas menyebut 270 menit, sedangkan total alokasi tabel simulasi 290 menit. Gunakan kesepakatan guru/asesor; timer portal dapat disesuaikan. Kode unit bertanda variasi versi harus divalidasi ke LSP sebelum digunakan sebagai perangkat resmi.",
    code: "[ ] Kebutuhan dan database\n[ ] Landing dan CRUD lengkap\n[ ] Validasi dan empty state\n[ ] Bug direproduksi dan diuji ulang\n[ ] TC-01 s.d. TC-10 + feature test\n[ ] README, screenshot, refleksi\n[ ] Presentasi dan verifikasi bukti",
    checkpoint:
      "Ekspor progres dan laporan. Tentukan tiga prioritas latihan berikutnya.",
    reference: 18,
  },
] as const;

export const cheatsheets = [
  {
    lang: "artisan",
    title: "Model, migration & controller",
    desc: "Buat tiga komponen dasar.",
    code: "php artisan make:model Product -mc",
  },
  {
    lang: "artisan",
    title: "Migration & seeder",
    desc: "migrate:fresh menghapus seluruh tabel; hanya untuk database latihan yang boleh direset.",
    code: "php artisan migrate\nphp artisan db:seed\n# Destruktif, opsional:\nphp artisan migrate:fresh --seed",
  },
  {
    lang: "laravel",
    title: "Resource route",
    desc: "Enam route CRUD yang dipakai jobsheet.",
    code: "Route::resource('produk', ProductController::class)->except(['show']);",
  },
  {
    lang: "php",
    title: "Validasi input",
    desc: "Konsisten dengan data dictionary jobsheet.",
    code: modules[3].code,
  },
  {
    lang: "php",
    title: "Simpan data tervalidasi",
    desc: "Gunakan hasil validate(), bukan seluruh input mentah.",
    code: "Product::query()->create($validated);\nreturn redirect()->route('produk.index')->with('success', 'Berhasil!');",
  },
  {
    lang: "blade",
    title: "Notifikasi berhasil",
    desc: "Tampilkan flash message dari session.",
    code: "@if(session('success'))\n  <p role=\"status\">{{ session('success') }}</p>\n@endif",
  },
  {
    lang: "blade",
    title: "Perulangan & empty state",
    desc: "Render data sekaligus kondisi kosong.",
    code: "@forelse($products as $produk)\n  <p>{{ $produk->nama_produk }} — Rp{{ number_format($produk->harga, 0, ',', '.') }}</p>\n@empty\n  <p>Belum ada produk.</p>\n@endforelse",
  },
  {
    lang: "blade",
    title: "Form hapus & CSRF",
    desc: "Konfirmasi sebelum menghapus.",
    code: "<form action=\"{{ route('produk.destroy', $produk) }}\" method=\"POST\"\n  onsubmit=\"return confirm('Hapus produk ini?')\">\n  @csrf @method('DELETE')\n  <button>Hapus</button>\n</form>",
  },
  {
    lang: "artisan",
    title: "Diagnosis aplikasi",
    desc: "Periksa route dan konfigurasi.",
    code: "php artisan route:list\nphp artisan config:clear\nphp artisan about\nphp artisan test",
  },
  {
    lang: "php",
    title: "Route Model Binding",
    desc: "Parameter $produk harus cocok dengan {produk}.",
    code: "public function edit(Product $produk) {\n  return view('produk.edit', compact('produk'));\n}",
  },
  {
    lang: "blade",
    title: "Old input & error",
    desc: "Pertahankan input setelah validasi gagal.",
    code: "<input name=\"nama_produk\" value=\"{{ old('nama_produk') }}\">\n@error('nama_produk')<p>{{ $message }}</p>@enderror",
  },
  {
    lang: "php",
    title: "Feature test",
    desc: "Gunakan database test terpisah dan RefreshDatabase.",
    code: "$response = $this->post('/produk', [\n  'nama_produk' => 'Kopi Aceh',\n  'deskripsi' => 'Aroma kuat',\n  'harga' => 22000,\n]);\n$response->assertRedirect(route('produk.index'));\n$this->assertDatabaseHas('products', ['nama_produk' => 'Kopi Aceh']);",
  },
];
export const flashcards = [
  {
    id: 1,
    category: "Skenario",
    q: "Apa entitas tunggal pada studi kasus ini?",
    a: "Tabel products. Fokusnya CRUD produk tanpa relasi banyak tabel.",
  },
  {
    id: 2,
    category: "Validasi",
    q: "Bagaimana aturan validasi harga?",
    a: "required|integer|min:0. Nilai nol valid; negatif, pecahan, dan teks ditolak.",
  },
  {
    id: 3,
    category: "Blade",
    q: "Apa fungsi directive @csrf?",
    a: "Menyertakan token CSRF untuk melindungi form mutasi pada aplikasi web Laravel.",
  },
  {
    id: 4,
    category: "Testing",
    q: "Berapa pengujian minimum pada jobsheet?",
    a: "Sepuluh skenario manual TC-01 sampai TC-10 dan minimal satu feature test Laravel.",
  },
  {
    id: 5,
    category: "Gambar",
    q: "Apakah upload gambar wajib?",
    a: "Tidak. Gambar berupa nama file yang tersedia pada public/images; field opsional dan perlu fallback.",
  },
  {
    id: 6,
    category: "Model",
    q: "Apakah $fillable menggantikan validasi?",
    a: "Tidak. $fillable membatasi mass assignment; validasi memeriksa keabsahan nilai input.",
  },
  {
    id: 7,
    category: "Migration",
    q: "Apa beda up() dan down()?",
    a: "up() menerapkan perubahan skema; down() membatalkan perubahan tersebut.",
  },
  {
    id: 8,
    category: "Controller",
    q: "Apa beda create() dan store()?",
    a: "create() menampilkan form tambah; store() memvalidasi dan menyimpan record baru.",
  },
  {
    id: 9,
    category: "Controller",
    q: "Apa beda edit() dan update()?",
    a: "edit() menampilkan form berisi data lama; update() memvalidasi dan menyimpan perubahan.",
  },
  {
    id: 10,
    category: "Routing",
    q: "Apa itu Route Model Binding?",
    a: "Laravel mencari model berdasarkan parameter route dan memasukkannya ke parameter method controller.",
  },
  {
    id: 11,
    category: "Model",
    q: "Apakah casts() membuat kolom database?",
    a: "Tidak. casts() mengubah representasi atribut model. Kolom dibuat melalui migration.",
  },
  {
    id: 12,
    category: "Blade",
    q: "Mengapa menggunakan @forelse?",
    a: "Untuk melakukan loop sekaligus menampilkan kondisi kosong melalui @empty.",
  },
  {
    id: 13,
    category: "Testing",
    q: "Apa beda expected dan actual result?",
    a: "Expected ditentukan sebelum pengujian; actual adalah hasil nyata setelah pengujian dijalankan.",
  },
  {
    id: 14,
    category: "Debugging",
    q: "Apa langkah pertama saat error?",
    a: "Reproduksi masalah dan catat pesan, file, baris, route, serta data sebelum mengubah kode.",
  },
  {
    id: 15,
    category: "Blade",
    q: "Mengapa @method diperlukan?",
    a: "Form HTML mengirim GET/POST. @method mensimulasikan PUT/PATCH/DELETE untuk routing Laravel.",
  },
  {
    id: 16,
    category: "Keamanan",
    q: "Bolehkah .env masuk repositori publik?",
    a: "Tidak. Berikan .env.example tanpa kredensial dan simpan rahasia di lingkungan masing-masing.",
  },
  {
    id: 17,
    category: "Database",
    q: "Mengapa nama_produk memiliki batas 100?",
    a: "Agar validasi string|max:100 selaras dengan kolom string(100) pada migration.",
  },
  {
    id: 18,
    category: "Dokumentasi",
    q: "Kapan proyek siap diserahkan?",
    a: "Saat fitur minimum lulus, error kritis selesai, pengujian dapat dijelaskan, dan bukti dokumentasi lengkap.",
  },
  {
    id: 19,
    category: "MVC",
    q: "Bagaimana produk sampai ke landing page?",
    a: "Controller query Product → collection products → compact ke Blade → @forelse merender produk.",
  },
  {
    id: 20,
    category: "SERKOM",
    q: "Apakah skor portal merupakan keputusan kompetensi?",
    a: "Tidak. Ini indikator latihan pribadi. Keputusan resmi ada pada asesor dan LSP.",
  },
];
export const fills = [
  {
    id: 1,
    title: "Route resource",
    before: "Route::",
    answer: "resource",
    after: "('produk', ProductController::class);",
    hint: "Membuat kumpulan route CRUD.",
  },
  {
    id: 2,
    title: "Ambil semua produk",
    before: "$products = Product::",
    answer: "all()",
    after: ";",
    hint: "Method Eloquent untuk seluruh record.",
  },
  {
    id: 3,
    title: "Konfirmasi hapus",
    before: "return ",
    answer: "confirm",
    after: "('Yakin ingin menghapus?');",
    hint: "Dialog konfirmasi bawaan JavaScript.",
  },
  {
    id: 4,
    title: "CSRF token",
    before: '<form method="POST">\n  @',
    answer: "csrf",
    after: "\n</form>",
    hint: "Proteksi form web dari request palsu.",
  },
  {
    id: 5,
    title: "Batas harga",
    before: "'harga' => 'required|integer|",
    answer: "min:0",
    after: "'",
    hint: "Nilai terkecil yang diperbolehkan adalah nol.",
  },
  {
    id: 6,
    title: "Data tervalidasi",
    before: "Product::query()->create(",
    answer: "$validated",
    after: ");",
    hint: "Variabel hasil $request->validate().",
  },
  {
    id: 7,
    title: "Empty state",
    before: "@forelse($products as $produk)\n  {{ $produk->nama_produk }}\n@",
    answer: "empty",
    after: "\n  Belum ada produk.\n@endforelse",
    hint: "Cabang untuk collection kosong.",
  },
  {
    id: 8,
    title: "Uji status HTTP",
    before: "$this->get('/')->",
    answer: "assertStatus",
    after: "(200);",
    hint: "Assertion untuk kode status respons.",
  },
];
export const problems = [
  {
    id: 1,
    title: "Hitung subtotal harga kopi",
    difficulty: "Mudah",
    fn: "hitungSubtotal",
    arg: "hargaArray",
    desc: "Jumlahkan seluruh angka dalam array. Array kosong harus menghasilkan 0.",
    hint: "Gunakan reduce dengan nilai awal 0 atau perulangan.",
    solution: "return hargaArray.reduce((total, harga) => total + harga, 0);",
    tests: [
      { args: [[15000, 20000, 25000]], expected: 60000 },
      { args: [[0, 10000]], expected: 10000 },
      { args: [[]], expected: 0 },
    ],
  },
  {
    id: 2,
    title: "Validasi harga minimal",
    difficulty: "Menengah",
    fn: "cekHarga",
    arg: "harga",
    desc: "Kembalikan true hanya untuk angka integer nonnegatif. String angka juga harus ditolak.",
    hint: "Gabungkan Number.isInteger() dengan >= 0.",
    solution: "return Number.isInteger(harga) && harga >= 0;",
    tests: [
      { args: [15000], expected: true },
      { args: [-500], expected: false },
      { args: [10.5], expected: false },
      { args: [0], expected: true },
      { args: ["12000"], expected: false },
    ],
  },
  {
    id: 3,
    title: "Format nama file gambar",
    difficulty: "Menengah",
    fn: "formatNamaGambar",
    arg: "namaProduk",
    desc: "Ubah semua huruf menjadi kecil, ganti setiap spasi dengan underscore, lalu tambahkan .jpg.",
    hint: "Gunakan toLowerCase() dan replaceAll().",
    solution: "return namaProduk.toLowerCase().replaceAll(' ', '_') + '.jpg';",
    tests: [
      { args: ["Kopi Sanger"], expected: "kopi_sanger.jpg" },
      { args: ["Arabica Super"], expected: "arabica_super.jpg" },
      { args: ["KOPI"], expected: "kopi.jpg" },
    ],
  },
  {
    id: 4,
    title: "Filter produk terjangkau",
    difficulty: "Menengah",
    fn: "filterProduk",
    arg: "products, batas",
    desc: "Kembalikan nama_produk dari setiap produk dengan harga <= batas, sesuai urutan asal.",
    hint: "Gunakan filter kemudian map.",
    solution:
      "return products.filter(p => p.harga <= batas).map(p => p.nama_produk);",
    tests: [
      {
        args: [
          [
            { nama_produk: "Sanger", harga: 18000 },
            { nama_produk: "Original", harga: 25000 },
          ],
          20000,
        ],
        expected: ["Sanger"],
      },
      { args: [[], 100], expected: [] },
      {
        args: [[{ nama_produk: "Gratis", harga: 0 }], 0],
        expected: ["Gratis"],
      },
    ],
  },
];
export const testCases = [
  [
    "TC-01",
    "Buka landing page /",
    "Tanpa data khusus",
    "HTTP 200; bagian utama tampil",
  ],
  [
    "TC-02",
    "Buka /produk saat kosong",
    "Tabel kosong",
    "Pesan belum ada produk",
  ],
  [
    "TC-03",
    "Tambah produk valid",
    "Kopi Aceh, deskripsi, 22000",
    "Tersimpan + success",
  ],
  [
    "TC-04",
    "Tambah tanpa nama",
    "Nama kosong",
    "Error required; tidak tersimpan",
  ],
  ["TC-05", "Harga huruf", "dua puluh ribu", "Error integer"],
  ["TC-06", "Harga negatif", "-1000", "Error min 0"],
  ["TC-07", "Edit produk", "Harga 24000", "Perubahan tersimpan"],
  ["TC-08", "Hapus produk", "Satu produk", "Terhapus setelah konfirmasi"],
  ["TC-09", "Gambar kosong", "null", "Gambar fallback tampil"],
  [
    "TC-10",
    "Landing setelah CRUD",
    "Data terbaru",
    "Landing menampilkan data terbaru",
  ],
];
export const portfolioItems = [
  "Source code Laravel lengkap",
  "README dan petunjuk instalasi",
  ".env.example tanpa rahasia",
  "Screenshot landing page",
  "Screenshot daftar, tambah, dan edit produk",
  "Bukti validasi input",
  "Laporan TC-01 s.d. TC-10",
  "Output feature test",
  "Log debugging sebelum dan sesudah",
  "Refleksi dan bahan presentasi",
];
export const nav = [
  { href: "/", label: "Overview", icon: "home" },
  { href: "/jobsheet", label: "Jobsheet", icon: "book" },
  { href: "/cheatsheet", label: "Cheatsheet", icon: "file" },
  { href: "/flashcards", label: "Flashcards", icon: "cards" },
  { href: "/fillcode", label: "Lengkapi kode", icon: "code" },
  { href: "/tantangan", label: "Tantangan kode", icon: "terminal" },
  { href: "/simulasi", label: "Simulasi ujian", icon: "timer" },
  { href: "/pengujian", label: "Pengujian & debugging", icon: "test" },
  { href: "/catatan", label: "Catatan & bookmark", icon: "note" },
  { href: "/portofolio", label: "Portofolio", icon: "folder" },
  { href: "/progress", label: "Progres belajar", icon: "chart" },
  { href: "/referensi", label: "Dokumen referensi", icon: "library" },
];
